permalink: /:categories/:title

collections:
  projects:
    output: true
    sort_by: position
  codex:
    output: true
    sort_by: position

highlighter: rouge

plugins:
  - jekyll-minifier
  - jekyll-katex

jekyll-minifier:
  uglifier_args: {}
